language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip
services:
  - postgresql
env:
  - STATIC_ROOT=/home/travis/bustimes-static/
  - DB_USER=postgres
  - DB_PASS=''
  - DEBUG=True
before_script:
  - pip install -r requirements-test.txt
  - psql -U postgres -c 'create extension postgis'
  - psql -U postgres -c 'create database bustimes'
  - ./manage.py migrate
  - gem install sass
  - npm install yuglify
  - ./manage.py collectstatic --noinput
script:
  - PYTHONWARNINGS=all coverage run manage.py test -v 3
  - pylint buses busstops departures txc | cat
  - flake8
after_success:
  coveralls
