language: python
cache: pip
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create extension postgis'
  - ./manage.py migrate
script:
  coverage run --source=buses,busstops,timetables manage.py test
after_success:
  coveralls
