language: python
cache: pip
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  psql -U postgres -c "create extension postgis"
script:
  coverage run --source=buses,busstops,timetables manage.py test
after_success:
  coveralls
