language: python
python:
  - "2.7"
  - "3.6"
cache: pip
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  - DB_USER=postgres DEBUG=True
before_install:
  - rvm install 2.2
  - nvm intall node
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt -r requirements-test.txt
  - gem install sass
  - npm install
before_script:
  - psql -U postgres -c 'create extension postgis'
  - psql -U postgres -c 'create database bustimes'
  - ./manage.py migrate
script:
  - ./manage.py collectstatic --noinput
  - PYTHONWARNINGS=all coverage run manage.py test
  - flake8
  - sass-lint 'busstops/static/css/*' -v
  - eslint 'busstops/static/js/*.js'
after_success:
  - coveralls
  - git status
