language: python
services:
  - postgresql
install:
  - pip install .
  - pip install -r requirements.txt
env:
  - DJANGO_SETTINGS_MODULE=buses.travis_settings
before_script:
  - psql -U postgres -c "create extension postgis"
script: ./manage.py test
