name: Python application
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: huaxk/postgis-action@v1
      with:
        postgresql version: '11'
    - name: Cache virtualenv
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
          ~/.local/share/pyppeteer
        key: ${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv
    - name: Install dependencies
      run: |
        pipenv sync --dev &
        sudo apt-get install binutils libproj-dev gdal-bin &
        wait
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      env:
        SECRET_KEY: wormprovision
        PGHOST: localhost
        PGUSER: postgres
        DB_NAME: postgres
      run: |
       pipenv run coverage run pytest
       pipenv run coverage run --append ./manage.py test
       pipenv run coverage html
    - name: Upload coverage
      uses: idlefingers/do-space-sync-action@0.1.0
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: htmlcov
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
        SPACE_REGION: ams3
        SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
